Repository cmheyselnat300713/capstone1-axion-dev-base, pull requests merged in 2022-10, with the labels that each got.

#162 Invitation rejects updates
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/modals/invitations/Cancel-invitation.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/constants.js
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
Labels: fix, feature, update, UI, connections, rc-8

#161 Close T-443 fix/duplicated school/university fields
  src/lib/collections/schools.js
Labels: fix, feature, rc-8

#163 Bug fix in accepted invitation
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
Labels: fix, update, connections, rc-8

#164 Fixed bug in sign in onMount
  src/routes/Signin.svelte
Labels: fix, update, rc-8

#165 invitation badge counter and reject fixes
  src/lib/components/MainAppHeader.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/routes/MainApp.svelte
Labels: fix, update, connections, rc-8

#166 Close T-442 FEATURE/ADD/invitations/ collaborations modal
  src/lib/components/MainAppHeader.svelte
  src/lib/components/User-Notification-Center/Notification-card.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/routes/MainApp.svelte
Labels: fix, feature, update, UI, connections, rc-8

#168 Close T-451 FEATURE/ADD/email verification
  src/lib/components/FAB/FAB.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/constants.js
  src/lib/interfaces/My-profile-interface.svelte
  src/routes/MainApp.svelte
  src/routes/Signup.svelte
Labels: feature, update, connections, rc-9

#169 Close T-450 terms and privacy links displays coming soon modals only
  src/routes/Signup.svelte
Labels: fix, feature, rc-9

#170 Close T-320 long subject/workspace names
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
Labels: fix, feature, rc-9

#171 Close T-453 FIX/courses sorting
  src/lib/components/MainAppHeader.svelte
  src/routes/Signup.svelte
Labels: fix, update, UI, connections, rc-9

#172 Close T-365 FEATURE/ADD/reset password UI
  src/lib/components/modals/password/get-email.svelte
  src/lib/components/modals/password/reset.svelte
  src/lib/stores/reset-password-store.js
  src/lib/validators.js
  src/routes/Signin.svelte
  src/routes/reset.svelte
Labels: feature, update, UI, connections, rc-9

#173 Close T-399 FIX/delete notification bug
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/Notification-card.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/routes/index.svelte
  static/axionFinalLogo.png
Labels: fix, update, connections, rc-9

#174 Close T-434 FIX/system notification fading @ sign up page
  src/SCSS/rotate.scss
  src/lib/components/System-Notification/Notification.svelte
  src/lib/validators.js
  src/routes/Signup.svelte
Labels: fix, update, UI, connections, rc-9

#175 Close T-396 FEATURE/ADD/unmarking subjects, etc. @ favorites
  src/app.scss
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
  src/routes/MainApp.svelte
Labels: fix, feature, update, UI, connections, rc-9

#176 Close T-338 feature/add/favorites interface
  src/lib/components/FAB/FAB.svelte
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/interfaces/Calendar-interface.svelte
  src/lib/interfaces/Favorites-interface.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/stores/favorites.js
  src/routes/MainApp.svelte
Labels: feature, update, UI, connections, rc-9

#177 Close T-339 feature/add/assigned to me interface
  src/lib/components/Assigne-to-me/task-view.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/invitations/invitations.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/interfaces/Assigned-to-me-interface.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/Favorites-interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/global-store.js
  src/routes/MainApp.svelte
Labels: fix, feature, update, UI, connections, rc-9

#179 Test of leaving the workspace
  src/lib/components/FAB/FAB.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/modals/subject/Add-subject-pop-up.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/workspace/Add-workspace-pop-up.svelte
  src/lib/components/modals/workspace/Leave-workspace.svelte
  src/lib/components/modals/workspace/Workspace-settings.svelte
  src/lib/interfaces/sub-interfaces/Boards-interface.svelte
  src/lib/stores/workspace.js
  src/routes/MainApp.svelte
Labels: fix, feature, update, UI, connections, rc-9

#178 Close T-456 contact us about google links
  src/routes/Contact.svelte
Labels: fix, feature, rc-9

#181 Fixed id of the owner
  src/lib/components/modals/workspace/Leave-workspace.svelte
Labels: fix, update, connections, rc-9

#183 Close T-457 FEATURE/ADD/leave-workspace-option
  src/lib/components/modals/workspace/Leave-workspace.svelte
Labels: fix, update, connections, rc-9

#184 Release candidate #9
  RC's.txt
  src/SCSS/rotate.scss
  src/app.scss
  src/lib/components/Assigne-to-me/task-view.svelte
  src/lib/components/FAB/FAB.svelte
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/Notification-card.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/interface-components/Member-Modal.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/boards/Add-board-modal.svelte
  src/lib/components/modals/boards/Board-settings.svelte
  src/lib/components/modals/deletions/Board-deletion.svelte
  src/lib/components/modals/deletions/Subject-deletions-modal.svelte
  src/lib/components/modals/deletions/Workspace-deletion.svelte
  src/lib/components/modals/invitations/Cancel-invitation.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/components/modals/invitations/invitations.svelte
  src/lib/components/modals/my profile/re-send-email-verifcation.svelte
  src/lib/components/modals/password/get-email.svelte
  src/lib/components/modals/password/reset.svelte
  src/lib/components/modals/subject/Add-subject-pop-up.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/components/modals/truncations/Subject-truncation-modal.svelte
  src/lib/components/modals/workspace/Add-workspace-pop-up.svelte
  src/lib/components/modals/workspace/Leave-workspace.svelte
  src/lib/components/modals/workspace/Workspace-settings.svelte
  src/lib/components/modals/workspace/components/Manage-admin-cards.svelte
  src/lib/config/constants.js
  src/lib/config/uploadPics.js
  src/lib/config/validators.js
  src/lib/interfaces/Assigned-to-me-interface.svelte
  src/lib/interfaces/Calendar-interface.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/Favorites-interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/interfaces/sub-interfaces/Boards-interface.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
  src/lib/stores/favorites.js
  src/lib/stores/global-store.js
  src/lib/stores/reset-password-store.js
  src/lib/stores/workspace.js
  src/routes/Contact.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/routes/experiment/profilePictureUpload/index.svelte
  src/routes/index.svelte
  src/routes/reset.svelte
  static/axionFinalLogo.png
Labels: fix, feature, Released RC, update, connections, rc-9

#185 Quick patch on realtime
  RC's.txt
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/modals/workspace/Leave-workspace.svelte
  src/routes/MainApp.svelte
Labels: fix, feature, update, connections, rc-10

#187 Fixed backURI
  src/lib/config/constants.js
Labels: fix

#188 Close T-472 fix/profile upload bug issue
  src/lib/components/MainAppHeader.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/my profile/edits/uploadPic.svelte
  src/lib/components/modals/my profile/re-send-email-verifcation.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/myProfile.js
Labels: fix, feature, update, UI, connections, rc-11

#189 Small patch for ui
  RC's.txt
  src/lib/components/MainAppHeader.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/my profile/edits/uploadPic.svelte
  src/lib/components/modals/my profile/re-send-email-verifcation.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/myProfile.js
Labels: fix, feature, update, UI, rc-11

#190 Fixed breadcrumbs issue on favorites -> workspace -> dashboard : board…
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
Labels: fix, update, UI, rc-11

#191 Close T-466 fix/delayed real-time changes (needs to refresh task)
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/components/modals/task/TaskRename.svelte
Labels: fix, update, UI, rc-11

#193 Close T-466 fix/Delayed real-time renaming the task
  src/lib/components/modals/task/TaskRename.svelte
Labels: fix, update, UI, rc-11

#194 Close T-475 fix/reloading other system page is moving to the subjects page
  src/lib/interfaces/My-profile-interface.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
Labels: fix, update, rc-11

#195 Close T-476 fix/cannot edit name, age, school, course and bio in my profile interface
  src/lib/components/FAB/FAB.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/my profile/edits/uploadPic.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/components/modals/workspace/viewMembers.svelte
  src/lib/config/uploadPics.js
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/myProfile.js
  src/lib/stores/workspace.js
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
Labels: fix, update, UI, connections, rc-11

#196 Close T-470 fix/logout confirmation modal
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/Notification-card.svelte
  src/lib/components/modals/boards/Add-board-modal.svelte
  src/lib/components/modals/deletions/Board-deletion.svelte
  src/lib/components/modals/deletions/Subject-deletions-modal.svelte
  src/lib/components/modals/deletions/Workspace-deletion.svelte
  src/lib/components/modals/invitations/Cancel-invitation.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/my profile/edits/uploadPic.svelte
  src/lib/components/modals/my profile/logout-confirmation.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/interfaces/Assigned-to-me-interface.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/interfaces/sub-interfaces/Boards-interface.svelte
  src/lib/stores/global-store.js
  src/lib/stores/myProfile.js
  src/routes/MainApp.svelte
  src/routes/Privacy_Policy.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/routes/Terms&Conditions.svelte
  src/routes/experiment/index.svelte
  src/routes/experiment/profilePictureUpload/index.svelte
Labels: fix, update, UI, rc-11

#197 Base testing rc for main axion
  src/lib/components/FAB/FAB.svelte
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/Notification-card.svelte
  src/lib/components/modals/boards/Add-board-modal.svelte
  src/lib/components/modals/deletions/Board-deletion.svelte
  src/lib/components/modals/deletions/Subject-deletions-modal.svelte
  src/lib/components/modals/deletions/Workspace-deletion.svelte
  src/lib/components/modals/invitations/Cancel-invitation.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/my profile/edits/uploadPic.svelte
  src/lib/components/modals/my profile/logout-confirmation.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/components/modals/workspace/viewMembers.svelte
  src/lib/config/uploadPics.js
  src/lib/interfaces/Assigned-to-me-interface.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/interfaces/sub-interfaces/Boards-interface.svelte
  src/lib/stores/global-store.js
  src/lib/stores/myProfile.js
  src/lib/stores/workspace.js
  src/routes/MainApp.svelte
  src/routes/Privacy_Policy.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/routes/Terms&Conditions.svelte
  src/routes/experiment/index.svelte
  src/routes/experiment/profilePictureUpload/index.svelte
Labels: fix, feature, Released RC, update, UI, connections, rc-11

#198 Close T-414 fix/unable to move the task from another board in mobile view
  src/lib/components/Assigne-to-me/task-view.svelte
  src/lib/components/Overlay.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/deletions/task-deletion.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/stores/taskStore.js
  src/routes/MainApp.svelte
Labels: fix, update, UI, connections, rc-11

#199 Early release of rc-11 to main task delete and mobile version of taskView
  src/lib/components/Assigne-to-me/task-view.svelte
  src/lib/components/Overlay.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/deletions/task-deletion.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/stores/taskStore.js
  src/routes/MainApp.svelte
Labels: fix, feature, update, UI, connections, rc-11

#200 Fixed bug on delete task
  src/lib/components/modals/deletions/task-deletion.svelte
  src/lib/config/channels functions/index.js
  src/lib/config/channels functions/task/index.js
  src/lib/config/channels functions/task/taskDeleted.js
  src/lib/config/channels.js
Labels: fix, connections, rc-11

#201 Close T-477 fix/updating basic information stuck up system notification
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/components/modals/viewDP.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/myProfile.js
Labels: fix, update, UI, rc-11

#202 Profile picture additions to view, bugs fixes
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/modals/my profile/edits/edit-basic.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/components/modals/viewDP.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/myProfile.js
Labels: fix, feature, update, UI, rc-11
