Repository cmheyselnat300713/capstone1-axion-dev-base, pull requests merged in 2022-09, with the labels that each got.

#135 Releasing Candidate - 6
  RC's.txt
  src/SCSS/background/color.scss
  src/SCSS/hover/bg.scss
  src/SCSS/position.scss
  src/app.scss
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/constants.js
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/stores/global-store.js
Labels: fix, feature, Released RC, update, UI, connections, rc-6

#136 Close T-411 fix/check symbols on board filters
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
Labels: fix, rc-7

#138 Close T-420 FEATURE/ADD/able to create a board in workspace
  src/lib/components/FAB/FAB.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/components/modals/Add-subject-pop-up.svelte
  src/lib/components/modals/Add-workspace-pop-up.svelte
  src/lib/components/modals/boards/Add-board-modal.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/sub-interfaces/Boards-interface.svelte
  src/lib/stores/global-store.js
Labels: fix, feature, update, UI, connections, rc-7

#140 Close T-427 fix/stuck at the subject modal and workspace modal when creating empty name
  src/lib/components/modals/subject/Add-subject-pop-up.svelte
  src/lib/components/modals/workspace/Add-workspace-pop-up.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
Labels: fix, update, UI, rc-7

#141 Close T-399 fix/error in deleting notification
  src/lib/components/User-Notification-Center/Notification-card.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/modals/boards/Add-board-modal.svelte
  src/lib/components/modals/subject/Add-subject-pop-up.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/workspace/Add-workspace-pop-up.svelte
Labels: fix, update, connections, rc-7

#143 Close T-428 FEATURE/ADD/manage admins in the workspace settings
  src/SCSS/hover/font/color.scss
  src/lib/components/FAB/FAB.svelte
  src/lib/components/modals/workspace/Add-workspace-pop-up.svelte
  src/lib/components/modals/workspace/Manage-admin-modal.svelte
  src/lib/components/modals/workspace/components/Manage-admin-cards.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/stores/global-store.js
  src/routes/Signin.svelte
Labels: fix, feature, update, UI, connections, rc-7

#142 Close T-425 change all 'truncate' word into 'reset' word
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/truncations/Subject-truncation-modal.svelte
  src/lib/interfaces/My-profile-interface.svelte
Labels: fix, rc-7

#144 Close T-430 FEATURE/ADD/Holding Subject box to open subject settings
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
Labels: feature, update, rc-7

#145 Close T-431 FIX/system notification display time
  src/lib/components/FAB/FAB.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification-container.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/TransitionOverlay.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/interface-components/Member-Modal.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Subject-Menu-Pop-Up.svelte
  src/lib/components/modals/boards/Add-board-modal.svelte
  src/lib/components/modals/deletions/Subject-deletions-modal.svelte
  src/lib/components/modals/subject/Add-subject-pop-up.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/components/modals/truncations/Subject-truncation-modal.svelte
  src/lib/components/modals/workspace/Add-workspace-pop-up.svelte
  src/lib/components/modals/workspace/components/Manage-admin-cards.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/stores/global-store.js
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
Labels: fix, rc-7

#148 Close T-439 feature/add/workspace settings modal
  src/lib/components/FAB/FAB.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/components/modals/deletions/Workspace-deletion.svelte
  src/lib/components/modals/workspace/Workspace-settings.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/stores/global-store.js
Labels: feature, update, UI, connections, rc-8

#149 Close T-438 FIX/edit subject name with empty name in subject settings
  src/lib/components/modals/boards/Board-settings.svelte
  src/lib/components/modals/subject/Subject-settings.svelte
  src/lib/components/modals/truncations/Subject-truncation-modal.svelte
  src/lib/components/modals/workspace/Workspace-settings.svelte
Labels: fix, update, connections, rc-8

#150 Close T-441 FIX/task card are shrinking after adding more tasks in boards
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
Labels: fix, update, UI, rc-8

#154 Fixed bug importing bcryptjs
  src/lib/components/modals/invitations/Cancel-invitation.svelte
Labels: fix, update, rc-8

#155 Fixed bug in uri in cancel invitation
  src/lib/components/modals/invitations/Cancel-invitation.svelte
Labels: fix, update, connections, rc-8

#151 Close T-356 Terms and conditions and privacy policy page
  src/routes/Privacy_Policy.svelte
  src/routes/Terms&Conditions.svelte
Labels: feature, UI, rc-8

#156 Fixed errors in canceling an invitation and listening events
  src/lib/components/modals/invitations/Cancel-invitation.svelte
  src/routes/MainApp.svelte
Labels: fix, update, connections, rc-8

#157 Fixes on pusher configs
  src/lib/components/MainAppHeader.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/routes/MainApp.svelte
Labels: fix, update, connections, rc-8

#158 Accept invitation feature integration
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/components/modals/invitations/invitations.svelte
  src/routes/MainApp.svelte
Labels: fix, feature, update, UI, connections, rc-8

#159 Bug fix on accept feature of invitations
  src/lib/components/modals/invitations/components/Invitation-box.svelte
  src/lib/components/modals/invitations/invitations.svelte
  src/routes/MainApp.svelte
Labels: fix, update, connections, rc-8

#160 invitation bugs
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/modals/invitations/components/Invitation-box.svelte
Labels: fix, update, connections, rc-8
