Repository cmheyselnat300713/capstone1-axion-dev-base, pull requests merged in 2022-08, with the labels that each got.

#127 Base update of task view modal
  package-lock.json
  package.json
  src/SCSS/background/color.scss
  src/SCSS/border/color.scss
  src/SCSS/border/index.scss
  src/SCSS/border/type.scss
  src/SCSS/border/width.scss
  src/SCSS/fonts/color.scss
  src/SCSS/fonts/index.scss
  src/SCSS/fonts/size.scss
  src/SCSS/hover/bg.scss
  src/SCSS/hover/parent.scss
  src/SCSS/index.scss
  src/SCSS/position.scss
  src/SCSS/resize.scss
  src/SCSS/rotate.scss
  src/app.scss
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/sub-interface-components/Task-box-pop-up-modal.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/Add-subject-pop-up.svelte
  src/lib/components/modals/Add-workspace-pop-up.svelte
  src/lib/components/modals/ComingSoonModal.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/interfaces/Assigned-to-me-interface.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
  src/lib/stores/global-store.js
  src/routes/Contact.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/variables.scss
Labels: feature, rc-5, update, UI

#129 T-380 feature/update/task view modal > task view data remerging locally
  src/lib/components/FAB/FAB.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/constants.js
  src/lib/interfaces/Dashboard-Interface.svelte
Labels: fix, rc-5, update, UI

#128 Close T-314 fix/axion allows the user to create workspace without naming it
  src/lib/components/modals/Add-subject-pop-up.svelte
  src/lib/components/modals/Add-workspace-pop-up.svelte
Labels: fix, rc-5

#130 Releasing Candidate - 5
  Procfile
  RC's.txt
  package-lock.json
  package.json
  src/SCSS/background/color.scss
  src/SCSS/border/color.scss
  src/SCSS/border/index.scss
  src/SCSS/border/type.scss
  src/SCSS/border/width.scss
  src/SCSS/fonts/color.scss
  src/SCSS/fonts/index.scss
  src/SCSS/fonts/size.scss
  src/SCSS/hover/bg.scss
  src/SCSS/hover/parent.scss
  src/SCSS/index.scss
  src/SCSS/position.scss
  src/SCSS/resize.scss
  src/SCSS/rotate.scss
  src/app.scss
  src/lib/components/FAB/FAB.svelte
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/sub-interface-components/Task-box-pop-up-modal.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/Add-subject-pop-up.svelte
  src/lib/components/modals/Add-workspace-pop-up.svelte
  src/lib/components/modals/ComingSoonModal.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/constants.js
  src/lib/interfaces/Assigned-to-me-interface.svelte
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
  src/lib/stores/global-store.js
  src/routes/Contact.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/variables.scss
Labels: Released RC, rc-5

#131 Close T-381 FIX/create task error
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
Labels: fix, connections, rc-6

#132 Close T-400 FIX/Axion header text is clickable
  src/lib/components/MainAppHeader.svelte
Labels: fix, UI, rc-6

#133 Close T-390 FEATURE/ADD/update of status of task
  src/SCSS/background/color.scss
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/components/modals/task/Add-task-pop-up.svelte
  src/lib/components/modals/task/Task-view-modal.svelte
  src/lib/constants.js
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/stores/global-store.js
Labels: feature, update, UI, connections, rc-6

#134 This merge includes the update on the backend-frontend connection link
  src/SCSS/hover/bg.scss
  src/SCSS/position.scss
  src/app.scss
  src/lib/components/MainAppDrawer-sidebar.svelte
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
  src/lib/components/interface-components/sub-interface-components/task/Task-card.svelte
  src/lib/constants.js
  src/lib/interfaces/Dashboard-Interface.svelte
  src/lib/stores/global-store.js
Labels: fix, update, rc-6
