Repository cmheyselnat300713/capstone1-axion-dev-base, pull requests merged in 2022-07, with the labels that each got.

#110 Close T-358 FIX/Fix modal opens at checkbox true
  src/routes/Signup.svelte
Labels: rc-4, fix

#111 Close T-359 FEATURE/ADD/my profile interface
  src/SCSS/background/color.scss
  src/SCSS/background/index.scss
  src/SCSS/fonts/index.scss
  src/SCSS/fonts/size.scss
  src/SCSS/index.scss
  src/SCSS/opacity.scss
  src/app.scss
  src/lib/interfaces/My-profile-interface.svelte
Labels: rc-4, feature

#112 Close T-360 feature/add/reset password link
  src/lib/interfaces/My-profile-interface.svelte
  src/routes/Signin.svelte
Labels: rc-4, feature

#113 Close T-362 fix/wrong notification on sign up
  src/routes/Signin.svelte
  src/routes/Signup.svelte
Labels: rc-4, fix

#114 Close T-297 feature/add/notification center
  src/SCSS/hover/index.scss
  src/SCSS/hover/opacity.scss
  src/SCSS/hover/parent.scss
  src/SCSS/index.scss
  src/SCSS/opacity.scss
  src/SCSS/position.scss
  src/SCSS/scale.scss
  src/app.scss
  src/lib/components/Home-header.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/Signup-header.svelte
  src/lib/components/System-Notification/Notification-container.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/sub-interface-components/Add-subject-pop-up.svelte
  src/lib/stores/global-store.js
  src/routes/Contact.svelte
  src/routes/Home.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/routes/index.svelte
Labels: rc-4, feature

#115 Close T-367 adding email addresses while searching for members
  src/lib/components/interface-components/Member modal/MemberBox.svelte
Labels: rc-4, feature

#116 Close T-368 fix/delete user notification
  src/SCSS/hover/parent.scss
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/sub-interface-components/Add-subject-pop-up.svelte
  src/lib/components/interface-components/sub-interface-components/Add-task-pop-up.svelte
  src/lib/components/interface-components/sub-interface-components/Add-workspace-pop-up.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
  src/routes/MainApp.svelte
Labels: rc-4, fix

#117 Close T-362 fix/wrong system notif on sign in page
  src/routes/Signin.svelte
Labels: rc-4, fix

#118 Close T-369 sign out button
  src/lib/interfaces/My-profile-interface.svelte
Labels: rc-4, fix

#119 Close T-376 edit user bio is not working
  src/lib/interfaces/My-profile-interface.svelte
Labels: rc-4, fix

#120 Close T-377 fix/age limiter at sign up page
  src/routes/Signup.svelte
Labels: rc-4, fix

#121 Close T-378 fix/able to sign up even not agreeing with the terms and condition and privacy policy (checkbox)
  src/routes/Signup.svelte
Labels: rc-4, fix

#122 Close T-379 Direct sign out
  src/lib/interfaces/My-profile-interface.svelte
Labels: rc-4, fix

#123 Close T-361 some misalignments
  src/lib/components/MainAppHeader.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/routes/Signup.svelte
Labels: rc-4, fix

#124 Releasing Candidate - 4
  RC's.txt
  package-lock.json
  package.json
  src/SCSS/background/color.scss
  src/SCSS/background/index.scss
  src/SCSS/fonts/index.scss
  src/SCSS/fonts/size.scss
  src/SCSS/hover/index.scss
  src/SCSS/hover/opacity.scss
  src/SCSS/hover/parent.scss
  src/SCSS/index.scss
  src/SCSS/opacity.scss
  src/SCSS/position.scss
  src/SCSS/scale.scss
  src/app.scss
  src/lib/collections/courses.js
  src/lib/collections/schools.js
  src/lib/components/Home-header.svelte
  src/lib/components/MainAppHeader.svelte
  src/lib/components/Signup-header.svelte
  src/lib/components/System-Notification/Notification-container.svelte
  src/lib/components/System-Notification/Notification.svelte
  src/lib/components/User-Notification-Center/NotificationCenter.svelte
  src/lib/components/interface-components/Member modal/MemberBox.svelte
  src/lib/components/interface-components/Subject-box.svelte
  src/lib/components/interface-components/sub-interface-components/Add-subject-pop-up.svelte
  src/lib/components/interface-components/sub-interface-components/Add-task-pop-up.svelte
  src/lib/components/interface-components/sub-interface-components/Add-workspace-pop-up.svelte
  src/lib/components/interface-components/sub-interface-components/Boards.svelte
  src/lib/components/interface-components/sub-interface-components/Task-card.svelte
  src/lib/components/interface-components/sub-interface-components/Workspace-box.svelte
  src/lib/constants.js
  src/lib/interfaces/My-profile-interface.svelte
  src/lib/interfaces/sub-interfaces/Subjects-interfaces.svelte
  src/lib/interfaces/sub-interfaces/Workspaces-interface.svelte
  src/lib/stores/global-store.js
  src/lib/uploadPics.js
  src/routes/Contact.svelte
  src/routes/Home.svelte
  src/routes/MainApp.svelte
  src/routes/Signin.svelte
  src/routes/Signup.svelte
  src/routes/experiment/index.svelte
  src/routes/experiment/profilePictureUpload/index.svelte
  src/routes/index.svelte
Labels: rc-4, Released RC

#125 Close T-382 'coming soon' modal in forgot password
  src/routes/Signin.svelte
Labels: fix, rc-5

#126 Close T-383 fix/signing out still possible in axion header
  src/lib/components/MainAppHeader.svelte
Labels: fix, rc-5
